### ISSUE TITLE
Improper Date Substitution

### ISSUE THREAD

**Issue by troycurtisjr** [LucHermitte/mu-template#2]
In `after/template/_/dollar_date.template` the else case contains a raw `<+lh#time#date()+>`, which puts the date on a new line which is not commented.  Thus when the file is sourced there is a syntax error.  This currently only appears to be used in the vim file templates, so putting a quote character ("), like in the `if` case, should resolve the error.  

However, I believe the intention of the template inclusion is for the date to not be on a separate line, but rather inline where it was included (for instance vim-header.template).

**Comment by LucHermitte** [comment]
Yes Indeed.

I have to refactor mu-template internals in order to support `<+s:Include(...)+>` correctly. The fact the line appear on a new line is a consequence of this improper implementation. I'll have revert to a previous version that did not have the issue you've observed.
