### ISSUE TITLE
Missing documentation on typical workflows

### ISSUE THREAD

**Issue by matthijskooijman** [LucHermitte/mu-template#6]
I found this repository, looking for a way to simplify some boilerplate code generation in my project. Looking at the feature list, I *think* that this can do exactly what I need, but I can't quite figure out how.

I've read the README, which mostly specifies what is available, and the documentation under `doc/`, which mostly specifies what moving parts are available, but I'm missing some actual examples of how you would use these templates (in particular snippets). Would you type the name of a snippet and then press a key combo? Or select a bit of text and then add a key combo? Would you enter the name of the snippet in a prompt?

Also, there is mention of placeholders, which also sound powerful, but I can't quite figure out what they are intended to do and how.

Note that this issue is not so much asking for help (I'll just experiment a bit and can probably figure things out), but a suggestion for adding some additional documentation.

**Comment by LucHermitte** [comment]
Thanks for your question. It'll help me improve the documentation.

To answer _quickly_ your question, and to start drafting what I have to add.

## Expanding a snippet
First of all, you need to remember the keybinding used to expand snippets, or chose one of your own. By default, snippet expansion is bound to `CTRL+R` then `TAB`. It can be changed into your `.vimrc` with for instance

```vim
" Overriding insert mode keybinding
imap <c-space>  <Plug>MuT_ckword
" Overriding visual mode keybinding
vmap <c-space>  <Plug>MuT_Surround
```

Then, let's say, you want to expand the `c/while` snippet in C or C++.

### In INSERT mode
Type, in insert mode, any sequence of **consecutive** characters appearing in the snippet name you want to expand (or an empty space if you want to chose from every known snippet -- for the current filetype), and trigger snippet expansion.

IOW, you can have a white space before hitting `<c-r><tab>` (or whatever you chose), `w`, `wh`,... `while` -- let's call it the _lead string_.
* If only one snippet matches, it's immediately expanded (like `if` in C and C++).
* If several snippets match, you can then type other characters from the snippet name to restrict the list of snippets shown.
    For instance, in C++, with lh-cpp installed, if you type: `w` and then hit `<c-r><tab>`,  you'll see a list of 11 snippet names with a short description. 
    Hitting `e` will restrict the list to all snippets than contain in order the lead string (`w`), plus the typed characters (`e` here), which leaves `cpp/weak_ptr`, `while-getline` and `while`. 
    You can continue to restrict the selection by hitting more characters, or moving around with the cursors.
    Select with `ENTER`, or `CTRL+Y`. Abort, with `ESCAPE`, `CTRL+E`...

There is a screencast in lh-cpp documentation: https://github.com/LucHermitte/lh-cpp/blob/master/doc/screencast-snippet-baseNV-class.gif


#### Note
At this time, there is a difference in behaviour between the _lead string_ and the characters typed afterward. `we<c-r><tab>` and `w<c-r><tab>e` won't give the same result. This is the choice I made after using the plugin for a very long time.

### In VISUAL mode
Snippets can be used to surround anything.

1. First, select what you wish to surround, possibly in a linewise fashion ([`:h linewise-visual`](http://vimhelp.appspot.com/visual.txt.html#linewise%2dvisual)), 
2. Then, hit the snippet expanding keybinding for visual mode (`<c-r><tab>` by default)
3. At the prompt, type a sequence of characters that appear at the start the snippet name you want to expand
4. If several snippets match, you'll have to chose one through a confirm box -- depending on whether you are using vim, or gvim, or some other option the exact UI may change.

If you don't abort, snippet will be expanded, and the first placeholder designated in the snippet will be replaced with the selection. In `c/while` case, the selection becomes the instructions looped over.

If you want to use the selection in another part of the snippet, given the snippet properly supports this, you'll have to type the number of the placeholder you'll have to be replaced with the selection before hitting the _expand_ keybinding. In `c/while` case, we can use something that will be used as the loop condition by typing 2 + `CTRL+R`+`TAB`


Unfortunately not all snippets are documented. I've started to take care of that in the case of C++ snippets in lh-cpp: https://github.com/LucHermitte/lh-cpp/blob/master/doc/snippets.md

In most cases, you'll have to edit the snippet to see what it does. It can be done with `:MUEdit`. Try for instance `:MUEdit c/while` (command-line expansion is supported).

### The placeholders
They are mark(er)s where the cursor can jump to. They are described in lh-brackets documentation.

By default, when the cursor jumps to a placeholder, this placeholder gets selected in SELECT-mode. Meaning, that everything we start typing is directly inserted in place of the placeholder text.

If several placeholders have the same name, `«cond»`, they will all get replaced simultaneously as we type if and only if [tomtom/stakeholders_vim](https://github.com/tomtom/stakeholders_vim) is installed.

IIRC, jumping from one placeholder to the next is described in [`:h markers`](http://vimhelp.appspot.com/lh-map-tools.txt.html#markers)

#### Note
The placeholder technology used in mu-template is one of the oldest in Vim ecosystem. It may seem less attractive than the ones from other plugins as the French quote characters appear. This is the one that has been introduced later on in latex-suite.

So far, I'm keeping these marker characters as they easily permit to jump forth, and back!
