### ISSUE TITLE
How to accept marker default value and jump to the next marker.

### ISSUE THREAD

**Issue by m-kru** [LucHermitte/mu-template#7]
Hi, I would like to know what is the default mapping for accepting marker default value and jumping to the next marker. 

By the way, I would like to comment, that this plugin looks like powerful and useful, however the entry point is really high.

**Comment by LucHermitte** [comment]
Yes indeed. The entry point is quite high. I'm sorry.

Marker related documentation is hidden in lh-brackets. As I use meta-mappings from gvim, I never remember the default mappings for people using vim in the terminal. Let me see... if you type `:h marker` and browse/read the next dozen of paragraphs, you'll see:

- How to change the default marker characters: `:SetMarker <+ +>` for instance.
- The default mappings for the various use cases. By default, jumping forward is bound to `<C-J>`.
- How to validate the text behind the marker, it's `<m-ins>` with gvim, and `<c-<>` with vim. To change it, you can change it with `:vmap µ <Plug>MarkersMap` -- actually, it toggles the presence of the marker characters around the selection.

**Comment by m-kru** [comment]
Is `<c-<>` a` Ctrl` + `<`? I can't get it to work.

**Comment by LucHermitte** [comment]
Yes. If your keyboard is not a US one, use the key were `<` is supposed to be on a US layout -- if this doesn't work, it means my choice for a default key is a very bad one. Remap it to something else in your .vimrc

    :vmap WHATEVER <Plug>MarkersMark 
    :nmap WHATEVER <Plug>MarkersMark
    :imap WHATEVER <Plug>MarkersMark
    " and not MarkersMap contrary to what I said before.

**Comment by m-kru** [comment]
I was not able to trigger it with Ctrl combination on my keyboard, after the remap it works. However, it still requires 2 actions to accept and go to the next marker. First accept `<custom mapping>` and then move `<C-j>`.

**Comment by LucHermitte** [comment]
Good point. You can easily have this feature with.

    :smap WHATEVER <Plug>MarkersMark<Plug>MarkersJump

By restricting the mapping to select-mode, this should avoid corner cases where `<Plug>MarkersMark` actually surrounds the selection/current word with marker characters, or just inserts a marker.
