### ISSUE TITLE
Global variable for status line.

### ISSUE THREAD

**Issue by m-kru** [LucHermitte/mu-template#8]
Is there any global variable, that can be used to display information on the status line, that user is currently fulfilling snippet?
**EDIT:**
This variable should be rather local to the current buffer.

**Comment by LucHermitte** [comment]
I don't keep this information. At best, all the information about the latest snippet expanded is available in `:echo lh#mut#debug('s:content')`. The thing is that mu-template snippets can _call_ other snippets. For instance, in C++, `switch` will _call_ `case`, and possibilly more than once.

What information would you like in that case, and for which purpose?

**Comment by m-kru** [comment]
I just would like to have an information on the status line, that there is at least one snippet in the current buffer that has not yet been fulfilled.

**Comment by LucHermitte** [comment]
Unlike the (/some?) other snippet engines, I don't maintain this information. We can know everything is filled when there is no more visible markers.  

When placeholders are invisible there is no way to know we have forgotten something as this is done with recent snippet engines. mu-template belongs to the early generation of snippet/template engines. Here, placeholders are recognised thanks to the extra marker characters that let us jump forward or backward. And while there is still some markers in the buffer, this means there is some unfinished business. What business, we cannot tell, but there is some.

At best, we can count the number of matches for `'\v'.lh#mut#debug('s:MarkerV(".{-}")')` in `getline(1, '$')` but this is likely to be very inefficient.

A big improvement in mu-template would to rewrite the expansion part to analyse the placeholders and provide what is done is stakeholder: kind of multicursor + keep information about placeholders that haven't been filled yet. It's not something I plan to do soon. May be vim9 new scripting language would be the right time to update mu-template...

**Comment by m-kru** [comment]
> mu-template belongs to the early generation of snippet/template engines. Here, placeholders are recognised thanks to the extra marker characters that let us jump forward or backward. 

This is actually what interested me in the `mu-template`. I have used UltiSnips so far, but there are no markers so you got no idea what else should be fulfilled, plus there are bugs in UltiSnips if you try to do more than if blocks or for loops. `mu-template` seems to have better designs goals, however it is really hard to start with. This is probably why it has only 15 stars so far.

**Comment by LucHermitte** [comment]
> I have used UltiSnips so far, but there are no markers so you got no idea what else should be fulfilled

What I usually do, is that I cycle (`<M-del>` for gvim/`<c-j>` for vim) until there is nothing left. 

>there are bugs in UltiSnips if you try to do more than if blocks or for loops

I definitively do things much more complex than simple control-statements. See the little screencast from lh-cpp `class` snippet: https://github.com/LucHermitte/lh-cpp/blob/master/doc/snippets.md#cppbase-class-non-virtual

> mu-template seems to have better designs goals

Thank you!

> This is probably why it has only 15 stars so far.

The dependencies, the invasive markers and the complex snippet syntax don't help ^^'

**Comment by m-kru** [comment]
You had great idea, something went wrong during the implementation process :wink:.
